# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.models.server import Server

class TestServer(unittest.TestCase):
    """Server unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Server:
        """Test Server
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Server`
        """
        model = Server()
        if include_optional:
            return Server(
                type = '',
                id = '',
                daemon_type = '',
                version = '',
                url = '',
                config_url = '',
                zones_url = ''
            )
        else:
            return Server(
        )
        """

    def testServer(self):
        """Test Server"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
