# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.api.servers_api import ServersApi


class TestServersApi(unittest.TestCase):
    """ServersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServersApi()

    def tearDown(self) -> None:
        pass

    def test_cache_flush_by_name(self) -> None:
        """Test case for cache_flush_by_name

        Flush a cache-entry by name
        """
        pass

    def test_list_server(self) -> None:
        """Test case for list_server

        List a server
        """
        pass

    def test_list_servers(self) -> None:
        """Test case for list_servers

        List all servers
        """
        pass


if __name__ == '__main__':
    unittest.main()
