# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.models.map_statistic_item_all_of_value import MapStatisticItemAllOfValue

class TestMapStatisticItemAllOfValue(unittest.TestCase):
    """MapStatisticItemAllOfValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MapStatisticItemAllOfValue:
        """Test MapStatisticItemAllOfValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapStatisticItemAllOfValue`
        """
        model = MapStatisticItemAllOfValue()
        if include_optional:
            return MapStatisticItemAllOfValue(
                name = '',
                value = ''
            )
        else:
            return MapStatisticItemAllOfValue(
        )
        """

    def testMapStatisticItemAllOfValue(self):
        """Test MapStatisticItemAllOfValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
