# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.api.apikey_api import ApikeyApi


class TestApikeyApi(unittest.TestCase):
    """ApikeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApikeyApi()

    def tearDown(self) -> None:
        pass

    def test_api_delete_apikey(self) -> None:
        """Test case for api_delete_apikey

        Delete the ApiKey with apikey_id
        """
        pass

    def test_api_generate_apikey(self) -> None:
        """Test case for api_generate_apikey

        Add a ApiKey key
        """
        pass

    def test_api_get_apikey_by_id(self) -> None:
        """Test case for api_get_apikey_by_id

        Get a specific apikey on the server, hashed
        """
        pass

    def test_api_get_apikeys(self) -> None:
        """Test case for api_get_apikeys

        Get all ApiKey on the server, except the actual key
        """
        pass

    def test_api_update_apikey(self) -> None:
        """Test case for api_update_apikey

        """
        pass


if __name__ == '__main__':
    unittest.main()
