# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_api_add_account_user(self) -> None:
        """Test case for api_add_account_user

        Link user to account
        """
        pass

    def test_api_add_user_account(self) -> None:
        """Test case for api_add_user_account

        Link user to account
        """
        pass

    def test_api_create_account(self) -> None:
        """Test case for api_create_account

        Add an Account
        """
        pass

    def test_api_list_account_users(self) -> None:
        """Test case for api_list_account_users

        List users linked to a specific account
        """
        pass

    def test_api_list_accounts(self) -> None:
        """Test case for api_list_accounts

        Get all Account entries
        """
        pass

    def test_api_list_users_account(self) -> None:
        """Test case for api_list_users_account

        List users linked to a specific account
        """
        pass

    def test_api_remove_account_user(self) -> None:
        """Test case for api_remove_account_user

        Unlink user from account
        """
        pass

    def test_api_remove_user_account(self) -> None:
        """Test case for api_remove_user_account

        Unlink user from account
        """
        pass


if __name__ == '__main__':
    unittest.main()
