# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.api.config_api import ConfigApi


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigApi()

    def tearDown(self) -> None:
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        Returns all ConfigSettings for a single server
        """
        pass

    def test_get_config_setting(self) -> None:
        """Test case for get_config_setting

        Returns a specific ConfigSetting for a single server
        """
        pass


if __name__ == '__main__':
    unittest.main()
