# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.models.api_update_user_request import ApiUpdateUserRequest

class TestApiUpdateUserRequest(unittest.TestCase):
    """ApiUpdateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiUpdateUserRequest:
        """Test ApiUpdateUserRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiUpdateUserRequest`
        """
        model = ApiUpdateUserRequest()
        if include_optional:
            return ApiUpdateUserRequest(
                username = '',
                password = '',
                plain_text_password = '',
                firstname = '',
                lastname = '',
                email = '',
                otp_secret = '',
                confirmed = '',
                role_name = '',
                role_id = ''
            )
        else:
            return ApiUpdateUserRequest(
        )
        """

    def testApiUpdateUserRequest(self):
        """Test ApiUpdateUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
