# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.models.rr_set import RRSet

class TestRRSet(unittest.TestCase):
    """RRSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RRSet:
        """Test RRSet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RRSet`
        """
        model = RRSet()
        if include_optional:
            return RRSet(
                name = '',
                type = '',
                ttl = 56,
                changetype = '',
                records = [
                    pdns_admin_client.models.record.Record(
                        content = '', 
                        disabled = True, 
                        set_ptr = True, )
                    ],
                comments = [
                    pdns_admin_client.models.comment.Comment(
                        content = '', 
                        account = '', 
                        modified_at = 56, )
                    ]
            )
        else:
            return RRSet(
                name = '',
                type = '',
                ttl = 56,
                changetype = '',
                records = [
                    pdns_admin_client.models.record.Record(
                        content = '', 
                        disabled = True, 
                        set_ptr = True, )
                    ],
        )
        """

    def testRRSet(self):
        """Test RRSet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
