# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.api.zonecryptokey_api import ZonecryptokeyApi


class TestZonecryptokeyApi(unittest.TestCase):
    """ZonecryptokeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ZonecryptokeyApi()

    def tearDown(self) -> None:
        pass

    def test_create_cryptokey(self) -> None:
        """Test case for create_cryptokey

        Creates a Cryptokey
        """
        pass

    def test_delete_cryptokey(self) -> None:
        """Test case for delete_cryptokey

        This method deletes a key specified by cryptokey_id.
        """
        pass

    def test_get_cryptokey(self) -> None:
        """Test case for get_cryptokey

        Returns all data about the CryptoKey, including the privatekey.
        """
        pass

    def test_list_cryptokeys(self) -> None:
        """Test case for list_cryptokeys

        Get all CryptoKeys for a zone, except the privatekey
        """
        pass

    def test_modify_cryptokey(self) -> None:
        """Test case for modify_cryptokey

        This method (de)activates a key from zone_name specified by cryptokey_id
        """
        pass


if __name__ == '__main__':
    unittest.main()
