# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.models.statistic_item import StatisticItem

class TestStatisticItem(unittest.TestCase):
    """StatisticItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatisticItem:
        """Test StatisticItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatisticItem`
        """
        model = StatisticItem()
        if include_optional:
            return StatisticItem(
                name = '',
                type = 'StatisticItem',
                value = ''
            )
        else:
            return StatisticItem(
        )
        """

    def testStatisticItem(self):
        """Test StatisticItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
