# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_admin_client.api.zones_api import ZonesApi


class TestZonesApi(unittest.TestCase):
    """ZonesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ZonesApi()

    def tearDown(self) -> None:
        pass

    def test_axfr_export_zone(self) -> None:
        """Test case for axfr_export_zone

        Returns the zone in AXFR format.
        """
        pass

    def test_axfr_retrieve_zone(self) -> None:
        """Test case for axfr_retrieve_zone

        Retrieve slave zone from its master.
        """
        pass

    def test_check_zone(self) -> None:
        """Test case for check_zone

        Verify zone contents/configuration.
        """
        pass

    def test_create_zone(self) -> None:
        """Test case for create_zone

        Creates a new domain, returns the Zone on creation.
        """
        pass

    def test_delete_zone(self) -> None:
        """Test case for delete_zone

        Deletes this zone, all attached metadata and rrsets.
        """
        pass

    def test_list_zone(self) -> None:
        """Test case for list_zone

        zone managed by a server
        """
        pass

    def test_list_zones(self) -> None:
        """Test case for list_zones

        List all Zones in a server
        """
        pass

    def test_notify_zone(self) -> None:
        """Test case for notify_zone

        Send a DNS NOTIFY to all slaves.
        """
        pass

    def test_patch_zone(self) -> None:
        """Test case for patch_zone

        Creates/modifies/deletes RRsets present in the payload and their comments. Returns 204 No Content on success.
        """
        pass

    def test_put_zone(self) -> None:
        """Test case for put_zone

        Modifies basic zone data (metadata).
        """
        pass

    def test_rectify_zone(self) -> None:
        """Test case for rectify_zone

        Rectify the zone data.
        """
        pass


if __name__ == '__main__':
    unittest.main()
