# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Server(BaseModel):
    """
    Server
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="Set to “Server”")
    id: Optional[StrictStr] = Field(default=None, description="The id of the server, “localhost”")
    daemon_type: Optional[StrictStr] = Field(default=None, description="“recursor” for the PowerDNS Recursor and “authoritative” for the Authoritative Server")
    version: Optional[StrictStr] = Field(default=None, description="The version of the server software")
    url: Optional[StrictStr] = Field(default=None, description="The API endpoint for this server")
    config_url: Optional[StrictStr] = Field(default=None, description="The API endpoint for this server’s configuration")
    zones_url: Optional[StrictStr] = Field(default=None, description="The API endpoint for this server’s zones")
    __properties: ClassVar[List[str]] = ["type", "id", "daemon_type", "version", "url", "config_url", "zones_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Server from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Server from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "id": obj.get("id"),
            "daemon_type": obj.get("daemon_type"),
            "version": obj.get("version"),
            "url": obj.get("url"),
            "config_url": obj.get("config_url"),
            "zones_url": obj.get("zones_url")
        })
        return _obj


