# coding: utf-8

"""
    PowerDNS Admin Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pdns_admin_client.models.pdns_admin_role import PDNSAdminRole
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    User that can access the gui/api
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The ID for this user (unique)")
    username: Optional[StrictStr] = Field(default=None, description="The username for this user (unique, immutable)")
    password: Optional[StrictStr] = Field(default=None, description="The hashed password for this user")
    firstname: Optional[StrictStr] = Field(default=None, description="The firstname of this user")
    lastname: Optional[StrictStr] = Field(default=None, description="The lastname of this user")
    email: Optional[StrictStr] = Field(default=None, description="Email addres for this user")
    otp_secret: Optional[StrictStr] = Field(default=None, description="OTP secret")
    confirmed: Optional[StrictBool] = Field(default=None, description="The confirmed status")
    role: Optional[PDNSAdminRole] = None
    __properties: ClassVar[List[str]] = ["id", "username", "password", "firstname", "lastname", "email", "otp_secret", "confirmed", "role"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of role
        if self.role:
            _dict['role'] = self.role.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "username": obj.get("username"),
            "password": obj.get("password"),
            "firstname": obj.get("firstname"),
            "lastname": obj.get("lastname"),
            "email": obj.get("email"),
            "otp_secret": obj.get("otp_secret"),
            "confirmed": obj.get("confirmed"),
            "role": PDNSAdminRole.from_dict(obj["role"]) if obj.get("role") is not None else None
        })
        return _obj


